### ISSUE TITLE
Compact Sign

### ISSUE THREAD

**Issue by t3ran13** [simplito/elliptic-php#19]
How to get compact sing for spec256k1 ?

it is the same to secp256k1_ecdsa_recoverable_signature_serialize_compact from 
https://github.com/bitcoin-core/secp256k1/blob/1e6f1f5ad5e7f1e3ef79313ec02023902bf8175c/include/secp256k1_recovery.h#L63

**Comment by ldudzsim** [comment]
Compact sign is DER encoded signature. You have example how to get it at main page https://github.com/simplito/elliptic-php#ecdsa.
It looks that secp256k1_ecdsa_recoverable_signature_serialize_compact should returns DER encoded signature, so yes it should be the same.

**Comment by t3ran13** [comment]
You are right, thx 
Some additionak magic is need

https://github.com/bitcoin-core/secp256k1/blob/e541a90ef6461007d9c6a74b9f9a7fb8aa34aaa8/src/modules/recovery/main_impl.h#L60
