### ISSUE TITLE
AdMob SSV Verification

### ISSUE THREAD

**Issue by KuLi** [simplito/elliptic-php#20]
Is it possible to verifcate admob server-side-verification? They use ECDSA with SHA256.

Given is a public key from https://www.gstatic.com/admob/reward/verifier-keys.json But how to use this key for verification?

AdMob Documentation: https://developers.google.com/admob/android/rewarded-video-ssv#manual_verification_of_rewarded_video_ssv

Can you help me?

**Comment by ldudzsim** [comment]
Our lib does not support parsing keys in PEM format. So at he beginning you have to parse it on your own. After that you can use standard verify method from [README](https://github.com/simplito/elliptic-php#ecdsa).

There was [topic about parsing key](https://github.com/simplito/elliptic-php/issues/13#issuecomment-494827254) and at the end somebody mention that to verify/sign you can just [use open_ssl](https://github.com/simplito/elliptic-php/issues/13#issuecomment-494830305), you can try it.

**Comment by appkoders** [comment]
@ldudzsim Do you know the format the signature the Admob is using?

Sample signature: `MEUCIQD3CcaS4UP436PO_lyvrppeY8ofuo1FQxKQtSPgEWpTBgIgFKLsFqduoMyjloSl_UsL77GXo8J95YTVkZPuNAegIE0`

I already parsed the keys but I dont know how to parse this properly.
