### ISSUE TITLE
Always the same sign

### ISSUE THREAD

**Issue by t3ran13** [simplito/elliptic-php#21]
i got the same sign for 2 differrent msg

782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de1**2909ce62ec5dc1c**862a5e0100086775657374313233086c697472626f6f6839707265646c61676179752d697a6d656e69742d616c676f7269746d792d656d69737369692d6762672d692d7679706c61742d6176746f72616d102700

782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de1**28b9cf23c3bef13**862a5e0100086775657374313233086c697472626f6f6839707265646c61676179752d697a6d656e69742d616c676f7269746d792d656d69737369692d6762672d692d7679706c61742d6176746f72616d102700

**Comment by ldudzsim** [comment]
Hmm what do you mean saying "the same"? They are different, you even highlighted the difference. They are ALMOST the same, I have to admit its quite rare and if you wanted to show us some fun example, yes it is fun, but still totally valid and expected :-)

**Comment by t3ran13** [comment]
This are messages, not sign

**Comment by ssmyczynski** [comment]
Message is expected to be a representation of big number, usually the result of applying a hash function to the message (e.g. sha256).

In first lines of EC->sign function you will see:
```php
$msg = $this->_truncateToN(new BN($msg, 16));
```
Mistery solved ;)

**Comment by t3ran13** [comment]
you are right, i forgot make hash :(
thx for help)
