### ISSUE TITLE
is it possible to get a 62 hex characters private key with this library ?

### ISSUE THREAD

**Issue by se8820726** [simplito/elliptic-php#31]
I have been using your library for a long time ( simplito/elliptic-php v1.0)

in order to generate private keys  for ethereum.

the size of ethereum private keys is 64 hex characters and the library always gave me private keys with 64 hex characters.

but recently it has given me a private key with 62 hex characters

is it possible?

this is my code:

```
$ec = new Elliptic\EC('secp256k1');
$key = $ec->genKeyPair();

$eth_privatekey = $key->getPrivate('hex');
$eth_publickey = $key->getPublic('hex');


var_dump($eth_privatekey );
var_dump($eth_publickey );
```

**Comment by ldudzsim** [comment]
Yes its possible. In average one of 256 keys has 31 bytes length (when you serialize it to hex it has 62 characters) it happens cause when you get random buffer with length 32 there is a chance 1 per 256 to get 0 in first byte. When you call
```
$key->getPrivate('hex');
```
you just convert BN to hex so this behaviour is expected, cause BN constructor just ignore all leading zeros. Our lib is about pure elliptic curves and do not support any standard serializing. When you want to serialize private key to some sort of format for example WIF you can use this code
```
    function toWIF($keyPair, $network = "80", $compressed = true) {
        $priv = $network . str_pad($keyPair->getPrivate("hex"), 64, "0", STR_PAD_LEFT);
        if( $compressed )
            $priv .= "01";

        return Base58::encodeHexWithChecksum($priv);
    }
 ```
