### ISSUE TITLE
with bip44,do mnemonic to address,Unable to get: uncompressed public key / address / Y coordinate

### ISSUE THREAD

**Issue by k6xiao** [simplito/elliptic-php#39]
PublicKey = ellipse X coordinate

uncompressedPublicKey = prefix 04 + ellipse X coordinate + ellipse y coordinate

$address = "0x" .substr(Keccak::hash(substr(hex2bin($uncompressedPublicKey), 1), 256), 24);
How to get the Y coordinate / uncompressed public key, and then get the address?

**Comment by k6xiao** [comment]
php:

I have calculated the private key / compressed public key from 12 mnemonics

How to continue to get the address?
```
use BIP\BIP44; //助记词生成种子，种子生成私钥公钥

// 助记词→私钥..
// mnemonic：助记词字符串 空格隔开
// passphrase：BIP39 密码（可选）
// address_index：地址索引
function mnemonic_to($mnemonic, $passphrase = '', $address_index = '0') {
    // $seed = Bip39::mnemonicToSeed(mnemonic, "pwd");
    $seed = hash_pbkdf2("sha512", $mnemonic, 'mnemonic' . $passphrase, 2048, 0, false);
    // 结构：m / purpose' / coin_type' / account' / change / address_index
    // purpose：44，
    // coin_type：60=以太坊，
    // account：代表这个币的账户索引，从0开始
    // change：0=外部(收款地址)，1=内部（也称为找零地址），ETH没有找零，所以一般是0
    // address_index：地址索引，从0开始，代表生成第几个地址
    $DerivationPath = "m/44'/60'/0'/0";
    $HDKey          = BIP44::fromMasterSeed($seed)->derive($DerivationPath . "/" . $address_index);
    dump($HDKey);
    $HDKey2 = BIP44::fromMasterSeed($seed)->derive($DerivationPath);
    dump($HDKey2);
    return [
        'privateKey'         => $HDKey->privateKey, //私钥-64字符-bip44第0个    BIP-32 主密钥?
        'publicKeyFull'      => '???', //未压缩公钥-130字符-前缀04+椭圆x坐标(64字符)+椭圆y坐标(64字符)
        'publicKey'          => $HDKey->publicKey, //压缩公钥-66字符-前缀03+x(如果y是奇数)，前缀02+x(如果y是偶数)
        'address'            => phpKeccak256($HDKey->publicKey), //地址-42字符
        'mnemonic'           => $mnemonic, //助记词-12个单词
        'wordsCount'         => count(explode(" ", $mnemonic)), //助记词数
        'entropy'            => BIP39::Words($mnemonic)->entropy, //熵
        'seed'               => $seed, // BIP39 种子
        'derivationPath'     => $DerivationPath, // BIP32 推导路径
        'privateExtendedKey' => $HDKey2->getPrivateExtendedKey(), //BIP32 扩展私钥
        'publicExtendedKey'  => $HDKey2->getPublicExtendedKey(), //BIP32 扩展公钥
        // 压缩公钥与未压缩公钥见   https://www.freesion.com/article/93101100036/
    ];
}
```

**Comment by ldudzsim** [comment]
To make this clear you have compressed public key from BIP44 library, and you ask us how to convert it to uncompressed version, so you need this code:
```php
 $ec = new EC('secp256k1');
 $key = $ec->keyFromPublic($HDKey->publicKey, 'hex');
 $uncompressedPublicKeyHex = $key->getPublic("hex");
```
Your corrected code:
```php
<?php
// composer require minter/minter-php-bip-44
// composer require kornrunner/keccak
// composer require furqansiddiqui/bip39-mnemonic-php

require_once("./vendor/autoload.php");

use Elliptic\EC;
use BIP\BIP44;
use kornrunner\Keccak;
use \FurqanSiddiqui\BIP39\BIP39;

var_dump(mnemonic_to('chicken home nothing witness quick credit post crystal omit once arrow digital'));

function pubKeyToAddress($pubkey) {
    return "0x" . substr(Keccak::hash(substr(hex2bin($pubkey->encode("hex")), 1), 256), 24);
}

function mnemonic_to($mnemonic, $passphrase = '', $address_index = '0') {
    $seed = hash_pbkdf2("sha512", $mnemonic, 'mnemonic' . $passphrase, 2048, 0, false);
    $DerivationPath = "m/44'/60'/0'/0";
    $HDKey          = BIP44::fromMasterSeed($seed)->derive($DerivationPath . "/" . $address_index);
    var_dump($HDKey);
    $HDKey2 = BIP44::fromMasterSeed($seed)->derive($DerivationPath);
    var_dump($HDKey2);
    $ec = new EC('secp256k1');
    $key = $ec->keyFromPublic($HDKey->publicKey, 'hex');
    $pubKey = $key->getPublic();
    return [
        'privateKey'         => $HDKey->privateKey,
        'publicKeyFull'      => '???',
        'publicKey'          => $HDKey->publicKey,
        'publicKeyUncompressed' => $pubKey->encode("hex"),
        'publicKeyUncompressed2' => $key->getPublic("hex"), // another way to do this
        'address'            => pubKeyToAddress($pubKey),
        'mnemonic'           => $mnemonic,
        'wordsCount'         => count(explode(" ", $mnemonic)),
        'entropy'            => BIP39::Words($mnemonic)->entropy,
        'seed'               => $seed,
        'derivationPath'     => $DerivationPath,
        'privateExtendedKey' => $HDKey2->getPrivateExtendedKey(),
        'publicExtendedKey'  => $HDKey2->getPublicExtendedKey(),
    ];
}
```

**Comment by k6xiao** [comment]
$pubKey = $key->getPublic(); //Wrong
$pubKey = $key->getPublic(false, 'hex'); //rignt

> To make this clear you have compressed public key from BIP44 library, and you ask us how to convert it to uncompressed version, so you need this code:
> 
> ```
>  $ec = new EC('secp256k1');
>  $key = $ec->keyFromPublic($HDKey->publicKey, 'hex');
>  $uncompressedPublicKeyHex = $key->getPublic("hex");
> ```
> 
> Your corrected code:
> 
> ```
> <?php
> // composer require minter/minter-php-bip-44
> // composer require kornrunner/keccak
> // composer require furqansiddiqui/bip39-mnemonic-php
> 
> require_once("./vendor/autoload.php");
> 
> use Elliptic\EC;
> use BIP\BIP44;
> use kornrunner\Keccak;
> use \FurqanSiddiqui\BIP39\BIP39;
> 
> var_dump(mnemonic_to('chicken home nothing witness quick credit post crystal omit once arrow digital'));
> 
> function pubKeyToAddress($pubkey) {
>     return "0x" . substr(Keccak::hash(substr(hex2bin($pubkey->encode("hex")), 1), 256), 24);
> }
> 
> function mnemonic_to($mnemonic, $passphrase = '', $address_index = '0') {
>     $seed = hash_pbkdf2("sha512", $mnemonic, 'mnemonic' . $passphrase, 2048, 0, false);
>     $DerivationPath = "m/44'/60'/0'/0";
>     $HDKey          = BIP44::fromMasterSeed($seed)->derive($DerivationPath . "/" . $address_index);
>     var_dump($HDKey);
>     $HDKey2 = BIP44::fromMasterSeed($seed)->derive($DerivationPath);
>     var_dump($HDKey2);
>     $ec = new EC('secp256k1');
>     $key = $ec->keyFromPublic($HDKey->publicKey, 'hex');
>     $pubKey = $key->getPublic();
>     return [
>         'privateKey'         => $HDKey->privateKey,
>         'publicKeyFull'      => '???',
>         'publicKey'          => $HDKey->publicKey,
>         'publicKeyUncompressed' => $pubKey->encode("hex"),
>         'publicKeyUncompressed2' => $key->getPublic("hex"), // another way to do this
>         'address'            => pubKeyToAddress($pubKey),
>         'mnemonic'           => $mnemonic,
>         'wordsCount'         => count(explode(" ", $mnemonic)),
>         'entropy'            => BIP39::Words($mnemonic)->entropy,
>         'seed'               => $seed,
>         'derivationPath'     => $DerivationPath,
>         'privateExtendedKey' => $HDKey2->getPrivateExtendedKey(),
>         'publicExtendedKey'  => $HDKey2->getPublicExtendedKey(),
>     ];
> }
> ```
