### ISSUE TITLE
How to get pulickey from a given privatekey? 

### ISSUE THREAD

**Issue by yupnano** [simplito/elliptic-php#4]
Hi , based on my current understanding, this elliptic-php can only generates private-public key pairs, and cannot generate  public key from a given private key. It that right?

Then how could I get pulickey from a given privatekey?

Many thanks if any information could be provided!

**Comment by ssmyczynski** [comment]
It is possible to generate public key for a given private key - see the code snippet below:

```php
$ec = new \Elliptic\EC('secp256k1');

$priv_hex = "751ce088f64404e5889bf7e9e5c280b200b2dc158461e96b921df39a1dbc6635";
$pub_hex = "03a319a1d10a91ada9a01ab121b81ae5f14580083a976e74945cdb014a4a52bae6";

$priv = $ec->keyFromPrivate($priv_hex);
if ($pub_hex == $priv->getPublic(true, "hex")) {
    echo "Success\n";
} else {
    echo "Fail\n";
}
```

We described API for ECDSA, EdDSA and ECDH but indeed forgot about basic EC interface :) - to be done.

**Comment by yupnano** [comment]
Thank you for the replay!
And I have another question, is this elliptic-php compatible with the secp256k1 used by BitCoin?

**Comment by yupnano** [comment]
Got it. Thank you so much!

**Comment by ssmyczynski** [comment]
@yupnano 
```php
$priv = $ec->keyFromPrivate($priv_hex);
$pub_hex = $priv->getPublic("hex");
```
instead of `$priv->getPublic(true, "hex")` in which case it returns compressed representation with '02' | '03' prefix.

**Comment by yupnano** [comment]
wow, thank you. I didn't find this from the code. I'll try it later.
