### ISSUE TITLE
EC recovery without Public key

### ISSUE THREAD

**Issue by digitaldonkey** [simplito/elliptic-php#5]
I'm trying to recover a Message, but I don't understand your params. 
Can you document them? 

https://github.com/simplito/elliptic-php/blob/be6b14c6999a5c328457d571f643ef8b3f3f82d0/lib/EC.php#L212-L214

Especially I don't understand what $j is (type and values). In my case I have a recovery param of 27, which wont work.

In your test it seems that you requiring the PubKey in order to recover it. 

https://github.com/simplito/elliptic-php/blob/d6c5ecaaf434a52449f5e8faa350311c9fd1dd7a/tests/ECDSATest.php#L300-L308

As you might know in the Ethereum world we don't really have a [publicKey, but a derivate of it](https://etherworld.co/2017/11/17/understanding-the-concept-of-private-key-public-key-and-address-in-ethereum-blockchain/). 

Can you provide a example of PubKey recovery which just requires Message+Signature?

**Comment by ssmyczynski** [comment]
The 3rd argument `$j` to `recoverPubKey` function is an integer in range 0 to 3 (in fact in most use cases just 0 or 1). 
In the Ethereum world your recovery param of 27 corresponds to value 0. 
For example see this snippet of code:

https://github.com/ethereumjs/ethereumjs-util/blob/7e3be1d97b4e11fbc4924836b8c444e644f643ac/index.js#L395-L403

In the test you mentioned the `getKeyRecoveryParam` function uses public key only to obtain the recovery param `$recid` (a number) which then later is used in `recoverPubKey`.

Just drop here valid message and signature and I will provide you a snippet of code to recover public key from them ;)

**Comment by ssmyczynski** [comment]
Following snippet made for fun - will be added to examples later:

```php
use Elliptic\EC;
use kornrunner\Keccak;

$ec = new EC('secp256k1');

$address   = "0x5a214a45585b336a776b62a3a61dbafd39f9fa2a";
$message   = "I like signatures";
// signature as returned by eth.sign(address, message)
$signature = "0xacb175089543ac060ed48c3e25ada5ffeed6f008da9eaca3806e4acb707b9481401409ae1f5f9f290f54f29684e7bac1d79b2964e0edcb7f083bacd5fc48882e1b";

$msglen = strlen($message);
$hash   = Keccak::hash("\x19Ethereum Signed Message:\n{$msglen}{$message}", 256);
$sign   = ["r" => substr($signature, 2, 64), "s" => substr($signature, 66, 64)];
$recid  = ord(hex2bin(substr($signature, 130, 2))) - 27; 

$pubKey = $ec->recoverPubKey($hash, $sign, $recid);

$address2 = "0x" . substr(Keccak::hash(substr(hex2bin($pubKey->encode("hex")), 1), 256), 24);

if ($address == $address2) {
    echo "Success\n";
} else {
    echo "Fail\n";
}
```

**Comment by digitaldonkey** [comment]
You are my hero :heart_eyes:
