### ISSUE TITLE
genKeyPair()参数

### ISSUE THREAD

**Issue by youfeed** [simplito/elliptic-php#7]
Can you customize the key to generate seeds?
Similar bitcoin

**Comment by fabeuluci** [comment]
When I am looking into code there is no method for doing this, but you can pass your own entropy to genKeyPair method

```<?php
use Elliptic\EC;
$ec = new EC('secp256k1');
$myEntropy = "......."; // insert here value from your custom random generator
$key = $ec->genKeyPair(array("entropy" => $myEntropy));```

**Comment by ssmyczynski** [comment]
If you just want to provide your own entropy then method described by @fabeuluci is the right one.
`genKeyPair` generates the key in deterministic way for the given entropy.

On other hand the usage of Mnemonic Codes (BIP32/39/44/141...) and generation of HD keys are not in the scope of this library, but can be easily implemented with use of it.
