### ISSUE TITLE
Probable problem in signing ethereum transactions by this library

### ISSUE THREAD

**Issue by se8820726** [simplito/elliptic-php#8]
I have problems in sending raw ethereum transactions.

when I want to send most of the times show me 'Invalid sender' error.
but sometimes tx is sent successfully.

I'm using your library for signing transactions.
I think that maybe the problem is from your library.
maybe your library don't sign transaction correctly or maybe I use it incorrectly.

please see my question in:
 https://ethereum.stackexchange.com/questions/59881/sending-ethereum-raw-transactions-by-infura-io-gives-me-invalid-sender-error
 and if you can help me for finding out the problem.

**Comment by ssmyczynski** [comment]
There is a PHP library `web3p/ethereum-tx` that is using `simplito/elliptic-php` and it works very well with the data you mentioned in your stackexchange question:
```php
<?php
require 'vendor/autoload.php';

use Web3p\EthereumTx\Transaction;

$nonce = 5;
$transaction = new Transaction([
    'nonce' => sprintf('x%x', $nonce),
    'gasPrice' => '0x3b9aca00',
    'gasLimit' =>  '0x8dda',
    'to' => '0x31d3b3b3c28e7d1bc213a36a52b7c25f12d42462',
    'value' => '0x0',
    'data' => '0xa9059cbb0000000000000000000000002cde56d79091a1fe2909eff1874d4843080c261f00000000000000000000000000000000000000000000000000000000000240a6',
    'chainId' => 3
]);

echo $transaction->hash(false) . PHP_EOL;

$signedTx = '0x' . $transaction->sign('6d797d79f5613074e7a27758e5fe5d56f3de090329e5426d14f8c6910a64430a');
echo $signedTx . PHP_EOL;
```

Actually the hash of the transaction and final serialized transaction hex produced by the code above are different from ones you sent in your stackexchange post:
hash: 
`7de30088adc07ab8c55ca6bcebf4eda262746edbf52d5b2db7bd24d0794fc5eb`
signed tx hex:
`0xf8aa827835843b9aca00828dda9431d3b3b3c28e7d1bc213a36a52b7c25f12d4246280b844a9059cbb0000000000000000000000002cde56d79091a1fe2909eff1874d4843080c261f00000000000000000000000000000000000000000000000000000000000240a62aa058e06b4232ddae4854571df23742a263cdfeb1902d2f687226200869ade30caba019d8e3468019bce05e9ecf44ac62d13e9e1fe31b80f11586b36e716790064be5`

I think that our library is ok ;)

**Comment by ssmyczynski** [comment]
BTW. I just used the code above with `$nonce = 14;` and broadcasted tx using https://ropsten.etherscan.io/pushTx
https://ropsten.etherscan.io/tx/0xb4a92948884d5d69ddd5febe8a25f220b866b7f4bb43d4ca564a2e8fede7afab
